GET http://localhost:3001/subjects HTTP/1.1
Content-Type: application/json

##############
GET http://localhost:3001/Question HTTP/1.1
Content-Type: application/json

####################
GET http://localhost:3001/results HTTP/1.1
Content-Type: application/json
####################
POST http://localhost:3001/users HTTP/1.1
Content-Type: application/json
####################
GET http://localhost:3001/subjects/5 HTTP/1.1
Content-Type: application/json

#####################
PATCH http://localhost:3001/users/d28a HTTP/1.1 
Content-Type: application/json

{
  "results": [
    {
      "score": 15,
      "date": "2025-09-22"
    }
  ]
}
